// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { envs } from './src/config/envs';

export default defineConfig({
  schema: "src/data/postgres/prisma/schema.prisma",
  migrations: {
    path: "src/data/postgres/prisma/migrations",
  },
  datasource: {
    url: envs.POSTGRES_URL,
  },
});
